name: tumbuh_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.7.0
  mobile_scanner: ^5.1.0
  camera: ^0.11.0+2
  dio: ^5.7.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"
  network_image_mock: ^2.1.1

flutter_launcher_icons:
  android: true
  ios: true
  # macos: true
  # windows: true
  # web:
  #   generate: true
  #   image_path: "assets/icons/app_icon.png"
  #   background_color: "#ffffff"
  #   theme_color: "#ffffff"
  image_path: "assets/icons/app_icon_ios.png"
  image_path_ios: "assets/icons/app_icon_ios.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_fg.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/Panduan/
    - assets/Panduan/Halaman Beranda/
    - assets/Panduan/Halaman Katalog Produk/
    - assets/Panduan/Halaman Katalog Produk/Produk saya/
    - assets/Panduan/Halaman Resep/
    - assets/Panduan/Halaman Resep/Resep pintar/
    - assets/Panduan/Halaman Scan/
    - assets/Panduan/Halaman Video Edukasi/
    - assets/Panduan/shell/
